site_name: Lite
site_description: Lite framework documentation
site_author: workframes
repo_url: https://github.com/workframes/Lite
repo_name: Lite

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.sections

nav:
  - Home: index.md
  - Getting Started: start.md
  - Communication:
    - Services: communication/services.md
    - Gates: communication/gates.md
  - Enviroment:
    - Instance: enviroment/instance.md
    - Assert: enviroment/assert.md
    - Promise: enviroment/promise.md
    - Table: enviroment/table.md
    - Enum: enviroment/enum.md
    - Tween: enviroment/tween.md
    - Http: enviroment/http.md
    - Proxy: enviroment/proxy.md
    - Webhook: enviroment/webhook.md
    - Firebase: enviroment/firebase.md


markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.progressbar
  - admonition

plugins:
  - search  

