site_name: Lite
site_description: Lite framework documentation
site_author: workframes
repo_url: https://github.com/workframes/Lite
repo_name: Lite

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.sections

nav:
  - Home: index.md
  - Getting Started: start.md
  - Communication:
    - Services: communication/services.md
    - Gates: communication/gates.md
  - Enviroment:
    - Instance: environment/instance.md
    - Assert: environment/assert.md
    - Promise: environment/promise.md
    - Table: environment/table.md
    - Enum: environment/enum.md
    - Tween: environment/tween.md
    - Http: environment/http.md
    - Proxy: environment/proxy.md
    - Webhook: environment/webhook.md
    - Firebase: environment/firebase.md


markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.progressbar
  - admonition

plugins:
  - search  

